// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const config = await fetch('/config.json').then(r => r.json()).catch(() => ({
  supabaseUrl: import.meta.env.VITE_SUPABASE_URL || "http://127.0.0.1:54321",
  anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH"
}));

export const supabase = createClient<Database>(config.supabaseUrl, config.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
