// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdwddtiysbjtjzbyknmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kd2RkdGl5c2JqdGp6Ynlrbm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjEyNjcsImV4cCI6MjA3MzQzNzI2N30.PEEQL_Py19kZSj9Qy0XAbycpfgdKmPFi_gBnsBKXwQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});