// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "http://localhost:54321";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93d3RiaWdpYnF1Z3RubmtkdWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NjM0MzYsImV4cCI6MjA3NDEzOTQzNn0.Pelf4sWwxbanWV-PMuNM2OWp6MeUIy7UDt8WT-U2D5s";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});